//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MyLT.rc
//
#define IDC_BTN_ADD                     2
#define IDC_BTN_INSERT                  3
#define IDC_BTN_DELFILE                 3
#define IDC_BTN_MODIFY                  4
#define IDC_BTN_DEL                     5
#define IDD_DLG_ABOUT                   100
#define IDR_MAINFRAME                   128
#define IDD_DLG_STATVIEW                131
#define IDD_DLG_NEWFILE                 133
#define IDD_DLG_DATAMANAGER             134
#define IDD_DLG_SELPERIOD               135
#define IDD_DLG_DATATRANS               136
#define IDD_DLG_SYSINFO                 138
#define IDB_3STATUS_BUTTON              143
#define IDD_DLG_OPENFILE                148
#define IDD_DLG_REGISTER                149
#define IDD_DLG_DOWNLOAD                150
#define IDR_AVI_DOWNLOAD                151
#define IDB_BMP_ANALYSE                 167
#define IDB_BMP_TRANS                   208
#define IDB_BMP_DOWN                    209
#define IDB_BMP_HELP                    211
#define IDB_BMP_MAIN                    212
#define IDB_BMP_NEW                     213
#define IDB_BMP_OPEN                    214
#define IDB_BMP_OPTIONS                 215
#define IDB_BMP_SAVE                    216
#define IDB_BMP_STAT                    217
#define IDD_DLG_RGNEDIT                 219
#define IDD_DLG_DRAWRES                 222
#define IDC_C_LST_MSG                   1000
#define IDC_A_CB_AVERET                 1002
#define IDC_B_CB_HF                     1003
#define IDC_B_CB_HT                     1004
#define IDC_B_CB_MF                     1005
#define IDC_B_CB_MT                     1006
#define IDC_B_CB_CF                     1007
#define IDC_B_CB_CT                     1008
#define IDC_B_LST_FILTER                1009
#define IDC_B_EDT_HAVE                  1012
#define IDC_B_CB_HMIN                   1014
#define IDC_B_CB_HMAX                   1015
#define IDC_A_CB_STATFROM               1016
#define IDC_A_CB_STATHISRET             1017
#define IDC_C_BTN_GO                    1018
#define IDC_C_PRO_PROCESS               1019
#define IDC_B_CB_VMIN                   1020
#define IDC_B_CB_HZMIN                  1021
#define IDC_C_BTN_NEXTPERIOD            1022
#define IDC_C_CB_PERIODNUM              1023
#define IDC_C_CK_MULTISEL               1024
#define IDC_C_BTN_CLEAR                 1025
#define IDC_C_BTN_SAVE                  1026
#define IDC_C_BTN_SAVENEXT              1027
#define IDC_C_BTN_STOPALL               1028
#define IDC_C_STC_MINIMSG               1029
#define IDC_A_STC_HOT                   1030
#define IDC_A_STC_MIDDLE                1031
#define IDC_A_STC_CODE                  1032
#define IDC_EDT_FILENAME                1033
#define IDC_B_CB_VMAX                   1033
#define IDC_BTN_BROSER                  1034
#define IDC_B_EDT_NOTHAVE               1034
#define IDC_CB_FROM                     1035
#define IDC_B_CB_FILTERF                1035
#define IDC_CB_TO                       1036
#define IDC_B_CB_FILTERT                1036
#define IDC_CB_FONTNAME                 1036
#define IDC_CK_HAVESPEC                 1037
#define IDC_B_CB_HZMAX                  1037
#define IDC_EDT_DESP                    1038
#define IDC_EDT_PERIOD                  1038
#define IDC_B_CB_VZMIN                  1038
#define IDC_CB_PERIOD                   1039
#define IDC_B_CB_VZMAX                  1039
#define IDC_EDT_DEVOTE                  1040
#define IDC_BTN_START                   1040
#define IDC_CB_SEPA                     1041
#define IDC_CB_DATE                     1042
#define IDC_CB_DEVOTE                   1043
#define IDC_CB_NO1                      1044
#define IDC_CB_NO2                      1045
#define IDC_CB_NO3                      1046
#define IDC_CB_NO4                      1047
#define IDC_CB_NO5                      1048
#define IDC_EDT_DATE                    1049
#define IDC_CB_NO6                      1049
#define IDC_STA_NO1                     1050
#define IDC_STA_NO2                     1051
#define IDC_STA_NO3                     1052
#define IDC_STA_NO4                     1053
#define IDC_STA_NO5                     1054
#define IDC_STA_NO6                     1055
#define IDC_STA_NO7                     1056
#define IDC_STA_NO8                     1057
#define IDC_BTN_EXIT                    1058
#define IDC_STA_PERIOD                  1058
#define IDC_CB_BEGINPERIOD              1059
#define IDC_STA_DATE                    1059
#define IDC_CB_ENDPERIOD                1060
#define IDC_CB_NO7                      1060
#define IDC_STA_DEVOTE                  1061
#define IDC_CB_NO8                      1062
#define IDC_CK_UPORDER                  1064
#define IDC_CK_AUTOLOAD                 1064
#define IDC_CK_ALLOWSEL                 1065
#define IDC_EDT_FILENAME2               1065
#define IDC_STATIC_CREDIT               1069
#define IDC_CB_NO_6                     1073
#define IDC_CB_NO_1                     1074
#define IDC_CB_NO_2                     1075
#define IDC_CB_NO_3                     1076
#define IDC_CB_NO_4                     1077
#define IDC_CB_NO_7                     1078
#define IDC_CB_NO_8                     1079
#define IDC_CB_NO_5                     1080
#define IDC_CB_PROVINCE                 1081
#define IDC_LST_PROVINCE                1084
#define IDC_CB_FILELIST                 1085
#define IDC_BTN_MOREINFO                1086
#define IDC_STA_MORE                    1089
#define IDC_STA_NORMAL                  1090
#define IDC_STA_MOREINFO                1091
#define IDC_ANI_DOWNLOAD                1091
#define IDC_BTN_GETFILELIST             1092
#define IDC_PRO_DOWNSTATE               1094
#define IDC_BTN_DOWN                    1097
#define IDC_STA_TOTALNUM                1098
#define IDC_STA_HTTPHOST                1098
#define IDC_STA_HAVEDOWNNUM             1099
#define IDC_STA_HOMEPAGE                1100
#define IDC_LST_TMPLIST                 1100
#define IDC_EDT_TMPNAME                 1101
#define IDC_BTN_TMPADD                  1102
#define IDC_BTN_TMPDEL                  1104
#define IDC_STA_TMPEDIT                 1105
#define IDC_B_STC_NOFILTER              1106
#define IDC_CB_CLRNAME                  1107
#define IDC_STA_COLOR                   1108
#define IDC_STA_FONT                    1109
#define IDC_CK_90                       1111
#define IDC_CK_180                      1112
#define IDC_CK_270                      1113
#define IDC_CK_HMIRROR                  1114
#define IDC_CK_VMIRROR                  1115
#define IDM_FILE_NEW                    32771
#define IDM_FILE_OPEN                   32772
#define IDM_FILE_SAVE                   32773
#define IDM_FILE_EXIT                   32774
#define IDM_DATA_MANAGER                32775
#define IDM_DATA_SELECT                 32776
#define IDM_DATA_TRANSDATA              32777
#define IDM_OPT_SYSSETUP                32778
#define IDM_NET_DOWNLOAD                32779
#define IDM_NET_UPDATE                  32780
#define IDM_NET_REGISTER                32781
#define IDM_HLP_CONTENT                 32782
#define IDM_HLP_ABOUT                   32783
#define IDM_VIEW_BEGIN                  33000
#define IDM_VIEW_MAIN                   33000
#define IDM_VIEW_ANALYSE                33001
#define IDM_VIEW_STAT                   33003
#define IDM_VIEW_END                    33199
#define IDS_PANEINFO_BEGIN              33200
#define IDS_INDICATOR_PROCESS           33201
#define IDS_INDICATOR_TOTALNUM          33202
#define IDS_INDICATOR_MSG               33203
#define IDS_INDICATOR_TIME              33204
#define IDS_PANEINFO_END                33299
#define IDC_DYNAMIC_BEGIN               33300
#define IDC_DYNAMIC_ANALYSE             33300
#define IDC_DYNAMIC_STAT                33301
#define IDC_DYNAMIC_FILTER              33302
#define IDC_DYNAMIC_SETUP               33303
#define IDC_DYNAMIC_LEFT                33304
#define IDC_DYNAMIC_RIGHT               33305
#define IDC_DYNAMIC_UP                  33306
#define IDC_DYNAMIC_BOTTON              33307
#define IDC_DYNAMIC_PAGEUP              33308
#define IDC_DYNAMIC_PAGEDOWN            33309
#define IDC_DYNAMIC_SCROLL              33310
#define IDC_DYNAMIC_END                 33399
#define IDM_DYNAMIC_MENU_BEGIN          33400
#define IDM_DYNAMIC_MENU_END            33499

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        223
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1112
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
